version: "3.8"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567899
      POSTGRES_DB: crude_server
    ports:
      - "5432:5432"
